import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://bop-meo.uat.m2m.telecom.pt/auth/realms/management.meo/protocol/openid-connect/auth?scope=openid&response_type=code&redirect_uri=https%3A%2F%2Fbop-meo.uat.m2m.telecom.pt%2Fbop%2Fauthentication%2FLogin.action&client_id=portal');
  await page.getByRole('textbox', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Login' }).fill('ptinadmin');
  await page.getByRole('textbox', { name: 'Login' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('123qwerty');
  await page.getByRole('button', { name: 'sign in' }).click();
  await page.locator('a').nth(4).click();
  await page.getByRole('link', { name: ' Service account' }).click();
  await page.getByRole('button', { name: '+ create' }).click();
  await page.getByRole('link', { name: 'Select a customer' }).click();
  await page.locator('#select2-drop-mask').click();
  await page.getByRole('button', { name: '+ create' }).click();
  await page.getByRole('textbox', { name: 'Customer name *' }).click();
  await page.getByRole('textbox', { name: 'Customer name *' }).fill('testcl');
  await page.getByRole('spinbutton', { name: 'VAT Number *' }).click();
  await page.getByRole('spinbutton', { name: 'VAT Number *' }).fill('124214212');
  await page.getByRole('textbox', { name: 'Phone * Contact number' }).click();
  await page.getByRole('textbox', { name: 'Phone * Contact number' }).fill('961234567');
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).fill('carlos.e.larramba@meo.pt');
  await page.getByRole('textbox', { name: 'Address *' }).click();
  await page.getByRole('img').first().click();
  await page.getByRole('img').first().click();
  await page.getByRole('checkbox', { name: 'Create billing account' }).check();
  await page.getByRole('button', { name: 'next ' }).click();
  await page.getByRole('checkbox', { name: 'Create service account' }).check();
  await page.getByRole('button', { name: 'next ' }).click();
  await page.locator('#input-catalogueOpts').click();
  await page.getByRole('radio').check();
  await page.getByRole('button', { name: 'select' }).click();
  await page.locator('#input-commercial-offer').click();
  await page.getByRole('row', { name: 'MEO Standard ' }).getByRole('radio').check();
  await page.getByRole('button', { name: 'select' }).click();
  await page.getByRole('button', { name: 'next ' }).click();
  await page.locator('div').filter({ hasText: /^GDPR ProtectionNoneDisabledEnabled$/ }).first().click();
  await page.getByLabel('GDPR Protection').selectOption('1');
  await page.getByRole('textbox', { name: 'Login*' }).click();
  await page.getByRole('textbox', { name: 'Login*' }).fill('carlos.e.larramba@meo.pt');
  await page.getByRole('textbox', { name: 'Name*' }).click();
  await page.getByRole('textbox', { name: 'Name*' }).fill('Carlos');
  await page.getByRole('textbox', { name: 'Mobile number*' }).click();
  await page.getByRole('textbox', { name: 'Mobile number*' }).fill('+351967165925');
  await page.getByRole('textbox', { name: 'Email*' }).click();
  await page.getByRole('textbox', { name: 'Login*' }).click();
  await page.getByRole('textbox', { name: 'Email*' }).click();
  await page.getByRole('textbox', { name: 'Email*' }).click();
  await page.getByRole('textbox', { name: 'Email*' }).fill('carlos.e.larramba@meo.pt');
  await page.getByLabel('Initial resource status').selectOption('preactive');
  await page.getByRole('spinbutton', { name: 'Maximum number*' }).click();
  await page.getByRole('spinbutton', { name: 'Maximum number*' }).click();
  await page.getByRole('spinbutton', { name: 'Maximum number*' }).click();
  await page.getByRole('spinbutton', { name: 'Maximum number*' }).fill('223');
  await page.getByRole('checkbox', { name: 'SMS' }).check();
  await page.locator('#df-id-dataPsTariffs28-selection-component-tokens').click();
  await page.getByRole('checkbox', { name: 'M2M_1MB_PPC_TM_PS_V2' }).check();
  await page.getByRole('button', { name: 'Clear all' }).click();
  await page.getByText('Tariff Plans sort Select all').first().click();
  await page.locator('#df-id-dataPsTariffs28-selection-component-tokens').click();
  await page.getByRole('checkbox', { name: 'M2M_1MB_PPC_TM_PS_V2' }).check();
  await page.locator('#df-id-apnList31').click();
  await page.locator('#df-id-dataPsDefaultTariff29').selectOption('41001');
  await page.getByRole('button', { name: 'Add Item' }).click();
  await page.getByRole('textbox', { name: 'Identifier*', exact: true }).click();
  await page.getByRole('textbox', { name: 'Identifier*', exact: true }).fill('internet');
  await page.getByRole('checkbox', { name: 'Service SMS Default' }).check();
  await page.locator('#df-id-smsTariffs56-selection-component-tokens').click();
  await page.getByRole('checkbox', { name: 'M2M_100_PPC_TM_SMS_V1' }).check();
  await page.getByText('Tariff Plans M2M_100_PPC_TM_SMS_V1 sort Select all').click();
  await page.getByRole('checkbox', { name: 'Resource diagnostic' }).check();
  await page.getByRole('button', { name: 'finish' }).click();
  await page.locator('#df-id-smsDefaultTariff57').selectOption('44001');
  await page.getByLabel('Type', { exact: true }).selectOption('PUBLIC');
  await page.getByLabel('IP type').selectOption('IPV4');
  await page.getByRole('checkbox', { name: '1st Fixed IP*' }).check();
  await page.locator('div').filter({ hasText: /^1st Fixed IP$/ }).click();
  await page.getByRole('button', { name: 'finish' }).click();
  await page.getByRole('checkbox', { name: '1st Fixed IP*' }).uncheck();
  await page.getByRole('button', { name: 'finish' }).click();
  await page.getByTitle('Add option to check on APN\'s').click();
  await page.getByTitle('Add option to check on APN\'s').click();
  await page.locator('#df-id-apnsDefault42 div').filter({ hasText: /^internet$/ }).click();
  await page.locator('input[name="internet"]').check();
  await page.getByRole('button', { name: 'finish' }).click();
  await page.goto('https://bop-meo.uat.m2m.telecom.pt/bop/accounts/AccountManagement.action#service-list');
});